export const products = [
  // ===== TRAKTION & INDUSTRI =====
  {
    slug: "gf-12-105v",
    name: "Sonnenschein GF 12 105 V",
    shortName: "GF 12 105 V",
    category: "traktion-industri",
    voltage: "12V",
    capacity: "105Ah (C₅) / 120Ah (C₂₀)",
    price: 4295,
    images: ["/produkter/gf12105v.png",
    badge: "Bästsäljare",
    description:
      "Högpresterande gel-batteri för truckar, golfbilar och industriella tillämpningar. Underhållsfritt med lång livslängd och djupcykelkapacitet.",
    specs: {
      Spänning: "12V",
      "Kapacitet (C₅)": "105Ah",
      "Kapacitet (C₂₀)": "120Ah",
      Typ: "Gel — Dryfit®",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
    },
  },
  {
    slug: "gf-12-160v",
    name: "Sonnenschein GF 12 160 V",
    shortName: "GF 12 160 V",
    category: "traktion-industri",
    voltage: "12V",
    capacity: "160Ah (C₅) / 196Ah (C₂₀)",
    price: 6495,
    images: ["/produkter/gf12160v.jpg",
    badge: null,
    description:
      "Kraftfullt gel-batteri för tunga traktionsapplikationer. Idealisk för större truckar och industrifordon som kräver lång drifttid.",
    specs: {
      Spänning: "12V",
      "Kapacitet (C₅)": "160Ah",
      "Kapacitet (C₂₀)": "196Ah",
      Typ: "Gel — Dryfit®",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
    },
  },
  {
    slug: "gf-12-076v",
    name: "Sonnenschein GF 12 76 V",
    shortName: "GF 12 76 V",
    category: "traktion-industri",
    voltage: "12V",
    capacity: "76Ah (C₅) / 86Ah (C₂₀)",
    price: 3695,
    images: ["/produkter/gf12076v.jpg",
    badge: null,
    description:
      "Mångsidig gel-batteri för medelstora truckar och industriella fordon. Kompakt design med pålitlig kraft.",
    specs: {
      Spänning: "12V",
      "Kapacitet (C₅)": "76Ah",
      "Kapacitet (C₂₀)": "86Ah",
      Typ: "Gel — Dryfit®",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
    },
  },
  {
    slug: "gf-06-240v",
    name: "Sonnenschein GF 6 240 V",
    shortName: "GF 6 240 V",
    category: "traktion-industri",
    voltage: "6V",
    capacity: "240Ah (C₅) / 270Ah (C₂₀)",
    price: 4895,
    images: ["/produkter/gf06240v.jpg",
    badge: null,
    description:
      "6V djupcykelbatteri med hög kapacitet för tunga traktionsapplikationer. Perfekt för golfbilar och elfordon.",
    specs: {
      Spänning: "6V",
      "Kapacitet (C₅)": "240Ah",
      "Kapacitet (C₂₀)": "270Ah",
      Typ: "Gel — Dryfit®",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
    },
  },
  {
    slug: "gf-06-180v",
    name: "Sonnenschein GF 6 180 V",
    shortName: "GF 6 180 V",
    category: "traktion-industri",
    voltage: "6V",
    capacity: "180Ah (C₅) / 200Ah (C₂₀)",
    price: 3995,
    images: ["/produkter/gf06180v.jpg",
    badge: null,
    description:
      "Kompakt 6V gel-batteri med utmärkt djupcykelkapacitet. Populärt val för golfbilar och lätta industrifordon.",
    specs: {
      Spänning: "6V",
      "Kapacitet (C₅)": "180Ah",
      "Kapacitet (C₂₀)": "200Ah",
      Typ: "Gel — Dryfit®",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
    },
  },
  {
    slug: "gf-12-050v",
    name: "Sonnenschein GF 12 50 V",
    shortName: "GF 12 50 V",
    category: "traktion-industri",
    voltage: "12V",
    capacity: "50Ah (C₅) / 55Ah (C₂₀)",
    price: 2795,
    images: ["/produkter/gf12050v.jpg",
    badge: null,
    description:
      "Kompakt 12V gel-batteri för mindre truckar och industriella tillämpningar. Enkel att installera och underhållsfri.",
    specs: {
      Spänning: "12V",
      "Kapacitet (C₅)": "50Ah",
      "Kapacitet (C₂₀)": "55Ah",
      Typ: "Gel — Dryfit®",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
    },
  },

  // ===== STÄDMASKINER =====
  {
    slug: "stad-gf-12-105v",
    name: "Sonnenschein GF 12 105 V Städ",
    shortName: "GF 12 105 V",
    category: "stadmaskiner",
    voltage: "12V",
    capacity: "105Ah (C₅) / 120Ah (C₂₀)",
    price: 4295,
    images: ["/produkter/gf12105v.png",
    badge: "Bästsäljare",
    description:
      "Det mest populära batteriet för professionella skurmaskiner. Gel-teknologi garanterar läckagefri drift och lång livslängd.",
    specs: {
      Spänning: "12V",
      "Kapacitet (C₅)": "105Ah",
      "Kapacitet (C₂₀)": "120Ah",
      Typ: "Gel — Dryfit®",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Användning: "Skurmaskiner, poleringsmaskiner",
    },
  },
  {
    slug: "stad-gf-12-076v",
    name: "Sonnenschein GF 12 76 V Städ",
    shortName: "GF 12 76 V",
    category: "stadmaskiner",
    voltage: "12V",
    capacity: "76Ah (C₅) / 86Ah (C₂₀)",
    price: 3695,
    images: ["/produkter/gf12076v.jpg",
    badge: null,
    description:
      "Pålitligt gel-batteri för medelstora städmaskiner. Perfekt balans mellan kapacitet och storlek.",
    specs: {
      Spänning: "12V",
      "Kapacitet (C₅)": "76Ah",
      "Kapacitet (C₂₀)": "86Ah",
      Typ: "Gel — Dryfit®",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Användning: "Medelstora skurmaskiner",
    },
  },
  {
    slug: "stad-gf-12-063y",
    name: "Sonnenschein GF 12 63 Y",
    shortName: "GF 12 63 Y",
    category: "stadmaskiner",
    voltage: "12V",
    capacity: "63Ah (C₅) / 70Ah (C₂₀)",
    price: 3195,
    images: ["/produkter/gf1263y.jpg",
    badge: null,
    description:
      "Kompakt gel-batteri med bärhandtag. Optimalt för mindre gångstyrda skurmaskiner och poleringsmaskiner.",
    specs: {
      Spänning: "12V",
      "Kapacitet (C₅)": "63Ah",
      "Kapacitet (C₂₀)": "70Ah",
      Typ: "Gel — Dryfit®",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Användning: "Mindre städmaskiner",
    },
  },
  {
    slug: "stad-gf-12-052y",
    name: "Sonnenschein GF 12 52 Y",
    shortName: "GF 12 52 Y",
    category: "stadmaskiner",
    voltage: "12V",
    capacity: "52Ah (C₅) / 60Ah (C₂₀)",
    price: 2895,
    images: ["/produkter/gf1252y.png",
    badge: null,
    description:
      "Litet gel-batteri med bärhandtag för kompakta städmaskiner. Enkel installation och läckagefritt.",
    specs: {
      Spänning: "12V",
      "Kapacitet (C₅)": "52Ah",
      "Kapacitet (C₂₀)": "60Ah",
      Typ: "Gel — Dryfit®",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Användning: "Kompakta städmaskiner",
    },
  },
  {
    slug: "stad-gf-06-180v",
    name: "Sonnenschein GF 6 180 V Städ",
    shortName: "GF 6 180 V",
    category: "stadmaskiner",
    voltage: "6V",
    capacity: "180Ah (C₅) / 200Ah (C₂₀)",
    price: 3995,
    images: ["/produkter/gf06180v.jpg",
    badge: null,
    description:
      "6V djupcykelbatteri för åkbara städmaskiner. Hög kapacitet ger lång drifttid även vid tung belastning.",
    specs: {
      Spänning: "6V",
      "Kapacitet (C₅)": "180Ah",
      "Kapacitet (C₂₀)": "200Ah",
      Typ: "Gel — Dryfit®",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Användning: "Åkbara städmaskiner",
    },
  },
  {
    slug: "stad-gf-12-050v",
    name: "Sonnenschein GF 12 50 V Städ",
    shortName: "GF 12 50 V",
    category: "stadmaskiner",
    voltage: "12V",
    capacity: "50Ah (C₅) / 55Ah (C₂₀)",
    price: 2795,
    images: ["/produkter/gf12050v.jpg",
    badge: null,
    description:
      "Kompakt instegsbatteri för mindre städmaskiner. Pålitlig gel-teknologi i en kostnadseffektiv modell.",
    specs: {
      Spänning: "12V",
      "Kapacitet (C₅)": "50Ah",
      "Kapacitet (C₂₀)": "55Ah",
      Typ: "Gel — Dryfit®",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Användning: "Mindre städmaskiner",
    },
  },

  // ===== STATIONÄRA =====
  {
    slug: "stat-gf-12-063y",
    name: "Sonnenschein GF 12 63 Y Stationär",
    shortName: "GF 12 63 Y",
    category: "stationara",
    voltage: "12V",
    capacity: "63Ah (C₅) / 70Ah (C₂₀)",
    price: 3195,
    images: ["/produkter/gf1263y.jpg",
    badge: "Populär",
    description:
      "Pålitligt gel-batteri för permobiler, elrullstolar och stationära larm-/hiss-system. Läckagefritt och vibrationståligt.",
    specs: {
      Spänning: "12V",
      "Kapacitet (C₅)": "63Ah",
      "Kapacitet (C₂₀)": "70Ah",
      Typ: "Gel — Dryfit®",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Användning: "Permobiler, hissar, larm",
    },
  },
  {
    slug: "stat-gf-12-052y",
    name: "Sonnenschein GF 12 52 Y Stationär",
    shortName: "GF 12 52 Y",
    category: "stationara",
    voltage: "12V",
    capacity: "52Ah (C₅) / 60Ah (C₂₀)",
    price: 2895,
    images: ["/produkter/gf1252y.png",
    badge: null,
    description:
      "Kompakt stationärt gel-batteri för UPS, nödbelysning och larmsystem. Pålitlig reservkraft dygnet runt.",
    specs: {
      Spänning: "12V",
      "Kapacitet (C₅)": "52Ah",
      "Kapacitet (C₂₀)": "60Ah",
      Typ: "Gel — Dryfit®",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Användning: "UPS, nödbelysning, larm",
    },
  },
  {
    slug: "stat-gf-12-050v",
    name: "Sonnenschein GF 12 50 V Stationär",
    shortName: "GF 12 50 V",
    category: "stationara",
    voltage: "12V",
    capacity: "50Ah (C₅) / 55Ah (C₂₀)",
    price: 2795,
    images: ["/produkter/gf12050v.jpg",
    badge: null,
    description:
      "Instegsbatteri för stationära system. Perfekt för mindre larmanläggningar och sprinklersystem.",
    specs: {
      Spänning: "12V",
      "Kapacitet (C₅)": "50Ah",
      "Kapacitet (C₂₀)": "55Ah",
      Typ: "Gel — Dryfit®",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Användning: "Larm, sprinkler",
    },
  },
  {
    slug: "stat-gf-12-076v",
    name: "Sonnenschein GF 12 76 V Stationär",
    shortName: "GF 12 76 V",
    category: "stationara",
    voltage: "12V",
    capacity: "76Ah (C₅) / 86Ah (C₂₀)",
    price: 3695,
    images: ["/produkter/gf12076v.jpg",
    badge: null,
    description:
      "Mellanstort gel-batteri för hissystem och större stationära installationer. Hög cykeltålighet.",
    specs: {
      Spänning: "12V",
      "Kapacitet (C₅)": "76Ah",
      "Kapacitet (C₂₀)": "86Ah",
      Typ: "Gel — Dryfit®",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Användning: "Hissar, stationära system",
    },
  },
  {
    slug: "stat-gf-12-105v",
    name: "Sonnenschein GF 12 105 V Stationär",
    shortName: "GF 12 105 V",
    category: "stationara",
    voltage: "12V",
    capacity: "105Ah (C₅) / 120Ah (C₂₀)",
    price: 4295,
    images: ["/produkter/gf12105v.png",
    badge: null,
    description:
      "Stort stationärt gel-batteri för krävande UPS-system och professionella reservkraftslösningar.",
    specs: {
      Spänning: "12V",
      "Kapacitet (C₅)": "105Ah",
      "Kapacitet (C₂₀)": "120Ah",
      Typ: "Gel — Dryfit®",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Användning: "UPS, reservkraft",
    },
  },
  {
    slug: "stat-drycell",
    name: "Sonnenschein Dry Cell 12V",
    shortName: "Dry Cell 12V",
    category: "stationara",
    voltage: "12V",
    capacity: "40Ah",
    price: 2295,
    images: ["/produkter/drycell.jpg",
    badge: null,
    description:
      "Kompakt dry cell-batteri för stationära tillämpningar med låg belastning. Extremt lång livslängd i standby.",
    specs: {
      Spänning: "12V",
      "Kapacitet": "40Ah",
      Typ: "Dry Cell",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Användning: "Standby, nödkraft",
    },
  },

  // ===== FRITID & SOLENERGI =====
  {
    slug: "fritid-gf-12-105v",
    name: "Sonnenschein GF 12 105 V Fritid",
    shortName: "GF 12 105 V",
    category: "fritid-solenergi",
    voltage: "12V",
    capacity: "105Ah (C₅) / 120Ah (C₂₀)",
    price: 4295,
    images: ["/produkter/gf12105v.png",
    badge: "Populär",
    description:
      "Storsäljare för husbilsägare och off-grid-system. Hög kapacitet med gel-teknik som tål djupcykling.",
    specs: {
      Spänning: "12V",
      "Kapacitet (C₅)": "105Ah",
      "Kapacitet (C₂₀)": "120Ah",
      Typ: "Gel — Dryfit®",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Användning: "Husbil, solceller, off-grid",
    },
  },
  {
    slug: "fritid-gf-12-076v",
    name: "Sonnenschein GF 12 76 V Fritid",
    shortName: "GF 12 76 V",
    category: "fritid-solenergi",
    voltage: "12V",
    capacity: "76Ah (C₅) / 86Ah (C₂₀)",
    price: 3695,
    images: ["/produkter/gf12076v.jpg",
    badge: null,
    description:
      "Kompakt fritidsbatteri för mindre husbilar och båtar. Gel-teknik som tål vibrationer och lutning.",
    specs: {
      Spänning: "12V",
      "Kapacitet (C₅)": "76Ah",
      "Kapacitet (C₂₀)": "86Ah",
      Typ: "Gel — Dryfit®",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Användning: "Husbil, båt",
    },
  },
  {
    slug: "fritid-gf-12-063y",
    name: "Sonnenschein GF 12 63 Y Fritid",
    shortName: "GF 12 63 Y",
    category: "fritid-solenergi",
    voltage: "12V",
    capacity: "63Ah (C₅) / 70Ah (C₂₀)",
    price: 3195,
    images: ["/produkter/gf1263y.jpg",
    badge: null,
    description:
      "Bärbart gel-batteri med handtag för båtar och stugor. Lätt att installera och flytta mellan säsonger.",
    specs: {
      Spänning: "12V",
      "Kapacitet (C₅)": "63Ah",
      "Kapacitet (C₂₀)": "70Ah",
      Typ: "Gel — Dryfit®",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Användning: "Båt, stuga, solenergi",
    },
  },
  {
    slug: "fritid-gf-12-050v",
    name: "Sonnenschein GF 12 50 V Fritid",
    shortName: "GF 12 50 V",
    category: "fritid-solenergi",
    voltage: "12V",
    capacity: "50Ah (C₅) / 55Ah (C₂₀)",
    price: 2795,
    images: ["/produkter/gf12050v.jpg",
    badge: null,
    description:
      "Instegsbatteri för mindre solcellsanläggningar och fritidsbehov. Pålitligt och underhållsfritt.",
    specs: {
      Spänning: "12V",
      "Kapacitet (C₅)": "50Ah",
      "Kapacitet (C₂₀)": "55Ah",
      Typ: "Gel — Dryfit®",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Användning: "Solceller, fritid",
    },
  },
  {
    slug: "fritid-gf-12-160v",
    name: "Sonnenschein GF 12 160 V Fritid",
    shortName: "GF 12 160 V",
    category: "fritid-solenergi",
    voltage: "12V",
    capacity: "160Ah (C₅) / 196Ah (C₂₀)",
    price: 6495,
    images: ["/produkter/gf12160v.jpg",
    badge: "Max kapacitet",
    description:
      "Största kapaciteten i sortimentet. Perfekt för krävande off-grid-system och stora solcellsinstallationer.",
    specs: {
      Spänning: "12V",
      "Kapacitet (C₅)": "160Ah",
      "Kapacitet (C₂₀)": "196Ah",
      Typ: "Gel — Dryfit®",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Användning: "Off-grid, solceller",
    },
  },
  {
    slug: "fritid-gf-06-240v",
    name: "Sonnenschein GF 6 240 V Fritid",
    shortName: "GF 6 240 V",
    category: "fritid-solenergi",
    voltage: "6V",
    capacity: "240Ah (C₅) / 270Ah (C₂₀)",
    price: 4895,
    images: ["/produkter/gf06240v.jpg",
    badge: null,
    description:
      "6V djupcykel med extrem kapacitet. Koppla i serie för 12V/24V-system i husbil eller off-grid.",
    specs: {
      Spänning: "6V",
      "Kapacitet (C₅)": "240Ah",
      "Kapacitet (C₂₀)": "270Ah",
      Typ: "Gel — Dryfit®",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Användning: "Off-grid, serie-koppling",
    },
  },
]

export function getProductsByCategory(slug) {
  return products.filter((p) => p.category === slug)
}

export function getProductImage(product) {
  return product.images?.[0] || "/produkter/placeholder.jpg"
}

export function getProductBySlug(slug) {
  return products.find((p) => p.slug === slug)
}

export function getAllCategories() {
  return [
    ...new Set(products.map((p) => p.category)),
  ]
}
