export const products = [
  // ===== TRAKTION & INDUSTRI (9 st) =====
  {
    slug: "nm125-6et",
    name: "Nordmax NM125-6ET – Traktionsbatteri 6V 240Ah",
    shortName: "NM 6V 240Ah",
    category: "traktion-industri",
    voltage: "6V",
    capacity: "240 Ah (C20)",
    price: 1836,
    images: ["/produkter/nm125-6et.jpg"],
    badge: "Populär",
    description:
      "Nordmax NM125-6ET levererar 240 Ah vid C20-urladdning och är det perfekta valet när du behöver extra kapacitet utöver standardmodellen NM105-6ET. Med 15 Ah högre kapacitet får du längre driftstid utan att behöva kompromissa på storlek – batteriet har samma yttermått (260 × 180 × 279 mm).\n\nBatteriet är designat för tunga cykliska applikationer som saxliftar, ledstaplare och större elfordon. Det ersätter direkt Trojan T-125 och är dimensionellt kompatibelt med alla installationer som använder BCI GC2-format.\n\nSom öppet blybatteri kräver NM125-6ET regelbunden vattenpåfyllning, men detta vägs upp av längre livslängd och bättre pris-prestanda. Rekommenderad laddström ligger på 20–40A för optimal livslängd.",
    inStock: true,
    specs: {
      Spänning: "6V",
      "Kapacitet (C20)": "240 Ah",
      Artikelnummer: "NM125-6ET",
      Mått: "260 × 180 × 279 mm",
      Typ: "Blybatteri, öppet (fritt ventilerat)",
      Ersätter: "Trojan T-125",
      Varumärke: "Nordmax",
    },
    metaDescription: "Nordmax NM125-6ET: 6V 240Ah traktionsbatteri med hög kapacitet för liftar, golfbilar och städmaskiner. Ersätter Trojan T-125. Snabb leverans.",
    fitsTo: "Liftar (JLG, Genie, Haulotte, Snorkel), golfbilar (36V/48V-system), pallyftare, städmaskiner, elfordon, solcellslagring.",
    recommendedCharger: "NOCO GX2440 (24V) eller GX3626EU (36V) beroende på systemspänning.",
    seoKeywords: "traktionsbatteri 6V 240Ah, Nordmax NM125, ersätter Trojan T-125, liftbatteri, golfbilsbatteri 6V 240Ah",
  },
  {
    slug: "nm305g-et",
    name: "Nordmax NM305G-ET – Traktionsbatteri 6V 330Ah",
    shortName: "NM 6V 330Ah",
    category: "traktion-industri",
    voltage: "6V",
    capacity: "330 Ah (C20)",
    price: 2796,
    images: ["/produkter/nm305g-et.jpg"],
    badge: null,
    description:
      "Nordmax NM305G-ET erbjuder 330 Ah kapacitet i 6V och är det rätta valet för medeltunga industriella applikationer. Batteriet sitter ofta i åkbara städmaskiner, mindre industrituckar och elfordon som kräver lång driftstid per laddning.\n\nMed måtten 296 × 176 × 366 mm är det kompaktare än storsyskonet NML16H-ET men levererar ändå kraftfull energi under hela arbetspasset. Batteriet följer internationell standard och är kompatibelt med installationer som använder BCI GC12-format.\n\nFör optimal livslängd rekommenderas regelbunden kontroll av vätskenivån och laddning efter varje användningscykel.",
    inStock: true,
    specs: {
      Spänning: "6V",
      "Kapacitet (C20)": "330 Ah",
      Artikelnummer: "NM305G-ET",
      Mått: "296 × 176 × 366 mm",
      Typ: "Blybatteri, öppet (fritt ventilerat)",
      Varumärke: "Nordmax",
    },
    metaDescription: "Nordmax NM305G-ET: Kraftigt 6V 330Ah traktionsbatteri för åkbara städmaskiner, industrituckar och tunga elfordon. Köp online.",
    fitsTo: "Åkbara städmaskiner (Nilfisk SC401/SC500, Hako Scrubmaster), industrituckar, tunga pallyftare, materialhantering.",
    recommendedCharger: "NOCO GX2440 (24V/40A) för 24V-system, GX3626EU (36V) för 36V-konfiguration.",
    seoKeywords: "traktionsbatteri 6V 330Ah, Nordmax NM305G, batteri städmaskin, industribatteri 6V, deep cycle 330Ah",
  },
  {
    slug: "nml16h-et",
    name: "Nordmax NML16H-ET – Traktionsbatteri 6V 420Ah",
    shortName: "NM 6V 420Ah",
    category: "traktion-industri",
    voltage: "6V",
    capacity: "420 Ah (C20)",
    price: 3196,
    images: ["/produkter/nml16h-et.jpg"],
    badge: "Mest kraft",
    description:
      "Nordmax NML16H-ET är det kraftigaste 6V-batteriet i Nordmax traktionssortiment, med imponerande 420 Ah kapacitet (C20). Det är specifikt utvecklat för tunga industriella applikationer där lång driftstid och hög strömbelastning krävs under hela arbetsdagen.\n\nMed en vikt på 52 kg och måtten 296 × 176 × 425 mm är detta ett robust batteri som ofta används i större åkbara städmaskiner, industrituckar och tunga materialhanteringsfordon. Batteriet klarar djupa urladdningar och återhämtar sig effektivt vid korrekt laddning.\n\nNML16H-ET följer internationell dimensionsstandard och fungerar som direkt ersättare i installationer som tidigare använt batterier i L16-format.",
    inStock: true,
    specs: {
      Spänning: "6V",
      "Kapacitet (C20)": "420 Ah",
      Artikelnummer: "NML16H-ET",
      Mått: "296 × 176 × 425 mm",
      Vikt: "52 kg",
      Typ: "Blybatteri, öppet (fritt ventilerat)",
      Varumärke: "Nordmax",
    },
    metaDescription: "Nordmax NML16H-ET: Kraftfullt 6V 420Ah traktionsbatteri för städmaskiner, truckar och tunga elfordon. 52 kg. Köp med snabb leverans.",
    fitsTo: "Åkbara städmaskiner (Nilfisk, Hako, Kärcher, Tennant), industrituckar, tunga materialhanteringsfordon, energilagring.",
    recommendedCharger: "NOCO GX2440 (24V) eller GX4820EU (48V) beroende på systemkonfiguration.",
    seoKeywords: "traktionsbatteri 6V 420Ah, Nordmax NML16H, batteri städmaskin stor, L16-batteri, industribatteri 6V",
  },
  {
    slug: "nm1275-12et",
    name: "Nordmax NM1275-12ET – Traktionsbatteri 12V 150Ah",
    shortName: "NM 12V 150Ah",
    category: "traktion-industri",
    voltage: "12V",
    capacity: "150 Ah (C20)",
    price: 2796,
    images: ["/produkter/nm1275-12et.jpg"],
    badge: null,
    description:
      "Nordmax NM1275-12ET ger dig 12 volt och 150 Ah i ett enda batteriblock – perfekt när du behöver hög spänning utan att seriekoppla flera 6V-batterier. Batteriet används ofta i kompakta liftar, mindre städmaskiner och servicefordon där utrymmet är begränsat.\n\nMed måtten 328 × 180 × 279 mm är NM1275-12ET kompakt nog för de flesta installationer och ersätter direkt liknande 12V-traktionsblock från Trojan och andra tillverkare.\n\nLämplig även för 24V-system där två batterier seriekopplas, eller 48V-system med fyra enheter. Den öppna konstruktionen med påfyllningsmöjlighet säkerställer maximal livslängd vid regelbundet underhåll.",
    inStock: true,
    specs: {
      Spänning: "12V",
      "Kapacitet (C20)": "150 Ah",
      Artikelnummer: "NM1275-12ET",
      Mått: "328 × 180 × 279 mm",
      Typ: "Blybatteri, öppet (fritt ventilerat)",
      Varumärke: "Nordmax",
    },
    metaDescription: "Nordmax NM1275-12ET: 12V 150Ah traktionsbatteri i ett enda block. Perfekt för 12V-liftar, små städmaskiner och elfordon. Köp här.",
    fitsTo: "Kompakta liftar, små åkbara städmaskiner, servicefordon, eltruckar, solcellsbanker, husbilssystem (12V).",
    recommendedCharger: "chAmp Pro 12V/30A (art.nr 0043890) för enstaka batteri, eller NOCO GX2440 för 24V-system.",
    seoKeywords: "traktionsbatteri 12V 150Ah, Nordmax NM1275, 12V liftbatteri, städmaskinsbatteri 12V, deep cycle 12V 150Ah",
  },
  {
    slug: "ev305a-a-am",
    name: "Discover EV305A-A – Dry Cell Traktionsbatteri 6V 330Ah",
    shortName: "Dry Cell 6V 330Ah",
    category: "traktion-industri",
    voltage: "6V",
    capacity: "330 Ah (C20)",
    price: 4156,
    images: ["/produkter/ev305a.jpg"],
    badge: "Underhållsfri",
    description:
      "Discover EV305A-A levererar imponerande 330 Ah vid 6V i Discovers beprövade Dry Cell-format. Detta är ett batteri för tunga industriella miljöer där påfyllning av batterivatten inte är praktiskt genomförbart.\n\nMed sin robusta AGM-konstruktion och hydropolymer-elektrolyt tål batteriet djupa urladdningar och hög belastning utan att tappa prestanda. Spillsäkerheten gör det möjligt att använda batteriet i känsliga miljöer som livsmedelsindustri och sjukvård.\n\nEV305A-A är idealiskt för åkbara städmaskiner och materialhanteringsfordon som används i flerskift.",
    inStock: true,
    specs: {
      Spänning: "6V",
      "Kapacitet (C20)": "330 Ah",
      Artikelnummer: "EV305A-A-AM",
      Mått: "295 × 180 × 345 mm",
      Typ: "Dry Cell (VRLA/AGM med hydropolymer)",
      Underhåll: "Underhållsfri",
      Spillsäkert: "Ja",
      Varumärke: "Discover",
    },
    metaDescription: "Discover EV305A-A: Kraftigt underhållsfritt 6V 330Ah Dry Cell batteri. Spillsäkert och vibrationståligt. För tunga städmaskiner och industri.",
    fitsTo: "Stora åkbara städmaskiner, industrituckar, materialhantering, AGV-system, livsmedels- och sjukvårdsmiljöer.",
    recommendedCharger: "NOCO GX2440 (24V/40A) i AGM-läge.",
    seoKeywords: "Discover Dry Cell 6V 330Ah, EV305A, underhållsfritt batteri industri, spillfritt traktionsbatteri, AGM 6V 330Ah",
  },
  {
    slug: "evl16a-a-m8",
    name: "Discover EVL16A-A – Dry Cell Traktionsbatteri 6V 390Ah",
    shortName: "Dry Cell 6V 390Ah",
    category: "traktion-industri",
    voltage: "6V",
    capacity: "390 Ah (C20)",
    price: 4796,
    images: ["/produkter/evl16a.jpg"],
    badge: null,
    description:
      "Discover EVL16A-A är det starkaste Dry Cell-batteriet i 6V-serien med hela 390 Ah kapacitet. Batteriet är konstruerat för de allra tyngsta applikationerna där du behöver maximal driftstid och absolut spillsäkerhet.\n\nMed Discovers patenterade hydropolymer-teknologi får du ett batteri som tål extrema vibrationer, djupa urladdningar och höga temperaturer – utan att någonsin behöva fylla på batterivatten.\n\nIdealiskt för flerskiftsdrift i lager, industri och städmaskinsapplikationer där driftstopp på grund av batteriunderhåll kostar pengar.",
    inStock: true,
    specs: {
      Spänning: "6V",
      "Kapacitet (C20)": "390 Ah",
      Artikelnummer: "EVL16A-A-M8",
      Mått: "295 × 180 × 385 mm",
      Typ: "Dry Cell (VRLA/AGM med hydropolymer)",
      Underhåll: "Underhållsfri",
      Spillsäkert: "Ja",
      Varumärke: "Discover",
    },
    metaDescription: "Discover EVL16A-A: Högkapacitets 6V 390Ah Dry Cell batteri. Underhållsfritt, spillsäkert. För tunga städmaskiner och industriella elfordon.",
    fitsTo: "Tunga åkbara städmaskiner, industrituckar, lagertransportfordon, AGV-system, högbelastade elfordon.",
    recommendedCharger: "NOCO GX2440 (24V) eller GX3626EU (36V) i AGM-läge.",
    seoKeywords: "Discover Dry Cell 6V 390Ah, EVL16A, traktionsbatteri tung industri, underhållsfritt 6V 390Ah, L16-batteri AGM",
  },
  {
    slug: "ev31a-a-m8",
    name: "Discover EV31A-A – Dry Cell Traktionsbatteri 12V 120Ah",
    shortName: "Dry Cell 12V 120Ah",
    category: "traktion-industri",
    voltage: "12V",
    capacity: "120 Ah (C20)",
    price: 3036,
    images: ["/produkter/ev31a.jpg"],
    badge: null,
    description:
      "Discover EV31A-A levererar 120 Ah vid 12V i ett kompakt Dry Cell-format. Batteriet är idealiskt för enklare liftar, små städmaskiner och servicefordon som drivs av ett enskilt 12V-batteri eller två i serie för 24V.\n\nMed Discovers Dry Cell-teknologi får du ett helt underhållsfritt batteri som aldrig läcker, oavsett höljets position. Det gör det perfekt för installationer där batteriet monteras i trånga utrymmen eller där regelbunden service är opraktiskt.\n\nBatteriet levererar jämn spänning genom hela urladdningscykeln och tål upprepade djupa urladdningar – en nyckelegenskap för traktionsanvändning.",
    inStock: true,
    specs: {
      Spänning: "12V",
      "Kapacitet (C20)": "120 Ah",
      Artikelnummer: "EV31A-A-M8",
      Mått: "330 × 172 × 236 mm",
      Typ: "Dry Cell (VRLA/AGM med hydropolymer)",
      Underhåll: "Underhållsfri",
      Spillsäkert: "Ja",
      Varumärke: "Discover",
    },
    metaDescription: "Discover EV31A-A: Kompakt 12V 120Ah Dry Cell batteri. Underhållsfritt, spillsäkert. Perfekt för 12V/24V-liftar och städmaskiner.",
    fitsTo: "Kompakta liftar, små städmaskiner, servicefordon, solcellslagring, husbilssystem, båtinstallationer.",
    recommendedCharger: "chAmp Pro 12V/30A (art.nr 0043890) eller 12V/15A (art.nr 0043880).",
    seoKeywords: "Discover Dry Cell 12V 120Ah, EV31A, underhållsfritt 12V batteri, AGM traktionsbatteri 12V, deep cycle 12V 120Ah",
  },
  {
    slug: "ev512a-150-m8",
    name: "Discover EV512A-150 – Dry Cell Traktionsbatteri 12V 150Ah",
    shortName: "Dry Cell 12V 150Ah",
    category: "traktion-industri",
    voltage: "12V",
    capacity: "150 Ah (C20)",
    price: 3916,
    images: ["/produkter/ev512a-150.png"],
    badge: null,
    description:
      "Discover EV512A-150 är det starkaste 12V Dry Cell-batteriet i sortimentet med 150 Ah kapacitet. Det är designat för applikationer som kräver hög energitäthet i ett enskilt 12V-block – eller som paras i serie för 24V/48V-system.\n\nMed den höga kapaciteten på 150 Ah får du längre driftstid jämfört med standardmodellen EV31A-A (120 Ah), utan att offra Discovers spillsäkerhet och underhållsfria design.\n\nBatteriet lämpar sig särskilt väl för professionella städmaskiner, liftar och elfordon där varje extra Ah innebär färre laddstopp under arbetsdagen.",
    inStock: true,
    specs: {
      Spänning: "12V",
      "Kapacitet (C20)": "150 Ah",
      Artikelnummer: "EV512A-150-M8",
      Mått: "341 × 173 × 288 mm",
      Typ: "Dry Cell (VRLA/AGM med hydropolymer)",
      Underhåll: "Underhållsfri",
      Spillsäkert: "Ja",
      Varumärke: "Discover",
    },
    metaDescription: "Discover EV512A-150: Högkapacitets 12V 150Ah Dry Cell batteri. Underhållsfritt och spillfritt. För liftar, städmaskiner och 24V-system.",
    fitsTo: "Professionella städmaskiner, liftar, servicefordon, 24V/48V-system, materialhantering, solcellslagring.",
    recommendedCharger: "chAmp Pro 12V/30A (art.nr 0043890) för enstaka batteri, NOCO GX2440 för 24V-par.",
    seoKeywords: "Discover Dry Cell 12V 150Ah, EV512A, traktionsbatteri 12V 150Ah underhållsfritt, spillsäkert 12V batteri, AGM deep cycle 150Ah",
  },
  {
    slug: "gf-06-240v",
    name: "Sonnenschein GF6240V – Gelbatteri 6V 240Ah",
    shortName: "GF 6V 240Ah",
    category: "traktion-industri",
    voltage: "6V",
    capacity: "240 Ah (C5) / 270 Ah (C20)",
    price: 4396,
    images: ["/produkter/gf06240v.jpg"],
    badge: null,
    description:
      "Sonnenschein GF 06 240 V är ett av de kraftfullaste gelbatterierna i Sonnenscheins sortiment med 240 Ah kapacitet (C5) och 270 Ah (C20). Det är konstruerat för tunga industriella applikationer där maximal driftstid och total underhållsfrihet krävs.\n\nMed 48 kg vikt och måtten 311 × 183 × 358 mm är detta ett robust batteri som typiskt används i stora åkbara städmaskiner, industritruckar och förarlösa transportsystem. Fyra enheter i serie ger ett 24V-system med enorm kapacitet.\n\nSonnenscheins gelteknologi eliminerar alla underhållskrav – ingen vattenpåfyllning, ingen syrakontroll, inga gasutsläpp. Batteriet klarar 700 djupa urladdningscykler och har en förväntad livslängd på 5–7 år vid korrekt laddning.",
    inStock: true,
    specs: {
      Spänning: "6V",
      "Kapacitet (C5)": "240 Ah",
      "Kapacitet (C20)": "270 Ah",
      Artikelnummer: "GF6240V",
      Mått: "311 × 183 × 358 mm",
      Vikt: "48 kg",
      Typ: "Gel (dryfit), helt underhållsfri",
      Cykellivslängd: "700 cykler",
      Tillverkad: "Tyskland",
      Varumärke: "Sonnenschein",
    },
    metaDescription: "Sonnenschein GF6240V: Kraftfullt 6V 240Ah gelbatteri. 700 cykler, 48 kg, Made in Germany. För tunga industri- och städmaskinsapplikationer.",
    fitsTo: "Stora åkbara städmaskiner (Nilfisk SC6000, Hako Scrubmaster B120, Kärcher BR 75/140), industrituckar, förarlösa transportsystem (FTS/AGV), tunga liftar, energilagring.",
    recommendedCharger: "NOCO GX2440 (24V/40A) – GEL-profil.",
    seoKeywords: "Sonnenschein GF6240V, gelbatteri 6V 240Ah, dryfit tung industri, underhållsfritt batteri stor städmaskin, Sonnenschein 6V premium",
  },

  // ===== STÄDMASKINER (4 st) =====
  {
    slug: "nm105-6et",
    name: "Nordmax NM105-6ET – Traktionsbatteri 6V 225Ah",
    shortName: "NM 6V 225Ah",
    category: "stadmaskiner",
    voltage: "6V",
    capacity: "225 Ah (C20)",
    price: 1756,
    images: ["/produkter/nm105-6et.jpg"],
    badge: "Prisvärd",
    description:
      "Nordmax NM105-6ET är ett öppet traktionsbatteri med en kapacitet på 225 Ah (C20) och 6 volts spänning. Batteriet är konstruerat för cyklisk användning där hög tillförlitlighet och lång livslängd krävs – exempelvis i golfbilar, personliftar, pallyftare och självgående städmaskiner.\n\nMed en hög cyklingstålighet klarar NM105-6ET frekventa laddnings- och urladdningscykler utan att förlora kapacitet. Batteriets mått (260 × 180 × 279 mm) följer internationell standard och är direkt kompatibelt med Trojan T-105 – du kan byta rakt av utan anpassningar.\n\nDet robusta polypropylen-höljet skyddar mot stötar och vibrationer, medan de noggrant utvalda blyplattorna säkerställer jämn energileverans genom hela urladdningscykeln. Nordmax batterier är utformade för nordiska förhållanden och presterar även vid lägre temperaturer.\n\nNM105-6ET är ett så kallat våtbatteri (flooded/fritt ventilerat), vilket innebär att batteriets elektrolyt är flytande. Detta kräver regelbunden kontroll och påfyllning av destillerat vatten, men ger i gengäld längre total livslängd och lägre inköpskostnad jämfört med underhållsfria alternativ.",
    inStock: true,
    specs: {
      Spänning: "6V",
      "Kapacitet (C20)": "225 Ah",
      "Kapacitet (C5)": "185 Ah",
      Artikelnummer: "NM105-6ET",
      Mått: "260 × 180 × 279 mm",
      Vikt: "ca 29 kg",
      Poltyp: "ELPT",
      Typ: "Blybatteri, öppet (fritt ventilerat)",
      Drifttemperatur: "-20°C till +45°C",
      Självurladdning: "5–15 % per månad",
      Ersätter: "Trojan T-105",
      Varumärke: "Nordmax",
    },
    metaDescription: "Nordmax NM105-6ET är ett kraftfullt 6V 225Ah traktionsbatteri för golfbilar, liftar och städmaskiner. Hög cykeltålighet, Trojan-kompatibelt. Köp online.",
    fitsTo: "Golfbilar (Club Car, E-Z-GO, Yamaha), personliftar (JLG, Genie, Haulotte), saxliftar, pallyftare, självgående städmaskiner, solcellslagring, elfordon, båtar.",
    recommendedCharger: "NOCO GX2440 (24V-system) eller chAmp Pro 24V/12A. Vid 36V-system används 6 st NM105-6ET i serie.",
    seoKeywords: "traktionsbatteri 6V 225Ah, Nordmax NM105, batteri golfbil 6V, ersätter Trojan T-105, liftbatteri 6V, städmaskinsbatteri",
  },
  {
    slug: "gf-12-063y",
    name: "Sonnenschein GF1263Y – Gelbatteri 12V 63Ah",
    shortName: "GF 12V 63Ah",
    category: "stadmaskiner",
    voltage: "12V",
    capacity: "63 Ah (C5)",
    price: 2636,
    images: ["/produkter/gf1263y.jpg"],
    badge: null,
    description:
      "Sonnenschein GF 12 063 Y erbjuder 63 Ah kapacitet (C5) i GF-Y-seriens beprövade format för mobility och fritid. Med 12V i ett enda block är det enkelt att installera i elrullstolar, scootrar och golfvagnar utan seriekoppling.\n\nJämfört med GF1252Y ger denna modell 21% mer kapacitet, vilket innebär märkbart längre räckvidd per laddning – särskilt värdefullt för aktiva rullstolsanvändare och golfspelare.\n\nDryfit-gelteknologin garanterar att batteriet är helt underhållsfritt och spillsäkert under hela sin livstid.",
    inStock: true,
    specs: {
      Spänning: "12V",
      "Kapacitet (C5)": "63 Ah",
      Artikelnummer: "GF1263Y",
      Mått: "261 × 171 × 210 mm",
      Typ: "Gel (dryfit), helt underhållsfri",
      Varumärke: "Sonnenschein",
    },
    metaDescription: "Sonnenschein GF1263Y: 12V 63Ah gelbatteri för elrullstolar, golfbilar och fritidsfordon. Underhållsfritt, 700 cykler. Made in Germany.",
    fitsTo: "Elrullstolar, elmopeder, golfvagnar, lätta elfordon, nödbelysning, solcellssystem.",
    recommendedCharger: "chAmp Pro 12V/15A (art.nr 0043880).",
    seoKeywords: "Sonnenschein GF1263Y, gelbatteri 12V 63Ah, rullstolsbatteri 63Ah, mobility batteri 12V, dryfit GF-Y 63Ah",
  },
  {
    slug: "gf-12-076v",
    name: "Sonnenschein GF1276V – Gelbatteri 12V 76Ah",
    shortName: "GF 12V 76Ah",
    category: "stadmaskiner",
    voltage: "12V",
    capacity: "76 Ah (C5) / 83 Ah (C20)",
    price: 2556,
    images: ["/produkter/gf12076v.jpg"],
    badge: null,
    description:
      "Sonnenschein GF 12 076 V erbjuder 76 Ah kapacitet (C5) i ett medelstort 12V-gelbatteri – perfekt balans mellan storlek och driftstid. Batteriet används flitigt i medelstora gångbakom-städmaskiner och mindre åkbara modeller.\n\nMed Sonnenscheins dryfit gel-teknologi får du ett batteri som är helt underhållsfritt, spillsäkert och gasningsfritt. Du kan placera det var som helst utan ventilation – en avgörande fördel i kompakta maskininstallationer.\n\nGF1276V klarar 700 djupa urladdningscykler och har en självurladdning på under 2% per månad, vilket gör det pålitligt även vid oregelbunden användning.",
    inStock: true,
    specs: {
      Spänning: "12V",
      "Kapacitet (C5)": "76 Ah",
      "Kapacitet (C20)": "83 Ah",
      Artikelnummer: "GF1276V",
      Mått: "330 × 171 × 236 mm",
      Vikt: "29 kg",
      Typ: "Gel (dryfit), helt underhållsfri",
      Cykellivslängd: "700 cykler",
      "Max laddström": "28,6 A",
      Tillverkad: "Tyskland",
      Varumärke: "Sonnenschein",
    },
    metaDescription: "Sonnenschein GF1276V: Tyskt 12V 76Ah gelbatteri med 700 cykler. Underhållsfritt, spillsäkert. Passar Nilfisk, Hako, Kärcher och fler.",
    fitsTo: "Medelstora städmaskiner (Nilfisk BA530, Hako Scrubmaster B30, Kärcher BR 40/25, Gansow CT45/CT70), elrullstolar, golfvagnar, solcellssystem.",
    recommendedCharger: "chAmp Pro 12V/30A (art.nr 0043890) – GEL-profil.",
    seoKeywords: "Sonnenschein GF1276V, gelbatteri 12V 76Ah, batteri Nilfisk BA530, dryfit 12V, underhållsfritt städmaskinsbatteri",
  },
  {
    slug: "gf-12-105v",
    name: "Sonnenschein GF12105V – Gelbatteri 12V 105Ah",
    shortName: "GF 12V 105Ah",
    category: "stadmaskiner",
    voltage: "12V",
    capacity: "105 Ah (C5) / 120 Ah (C20)",
    price: 3596,
    images: ["/produkter/gf12105v.png"],
    badge: "Bästsäljare",
    description:
      "Sonnenschein GF 12 105 V är flaggskeppet bland 12V gelbatterier med 105 Ah kapacitet (C5) och 120 Ah (C20). Det är det mest använda gelbatteriet i professionella städmaskiner i Europa och har byggt sitt rykte på oöverträffad cykellivslängd.\n\nMed 700 cykler vid 75% urladdningsdjup (IEC 60254-1) har ingen konkurrent lyckats matcha Sonnenscheins gelteknologi. Hemligheten ligger i dryfit-processen där batterisyran binds i en gelé som stabiliserar blyplattorna och förhindrar sulfatering.\n\nBatteriet väger 40 kg och har måtten 345 × 174 × 283 mm. Det används i hundratals städmaskins- och industrifordon världen över, från Nilfisk och Hako till Gansow och Comac.\n\nGF12105V kan inte kortsluta internt tack vare att ingen aktiv substans samlas i batteriet. Det bildar inga gaser vid normal laddning och kan säkert placeras i slutna utrymmen. Det finns ingen risk för syraskiktning – batteriet behöver aldrig 'kokas' eller överladdas.",
    inStock: true,
    specs: {
      Spänning: "12V",
      "Kapacitet (C5)": "105 Ah",
      "Kapacitet (C20)": "120 Ah",
      Artikelnummer: "GF12105V",
      Mått: "345 × 174 × 283 mm",
      Vikt: "40 kg",
      Poltyp: "Konisk",
      Typ: "Gel (dryfit), helt underhållsfri",
      Cykellivslängd: "700 cykler (IEC 60254-1)",
      "Max laddström": "40 A",
      Tillverkad: "Tyskland",
      Varumärke: "Sonnenschein",
    },
    metaDescription: "Sonnenschein GF12105V: Premium 12V 105Ah gelbatteri. 700 cykler, Made in Germany. Passar Nilfisk BA451, Gansow, Hako och fler.",
    fitsTo: "Professionella städmaskiner (Nilfisk BA451D, BA530, Hako Scrubmaster B45, Kärcher BR 55/40, Gansow CT45/CT80/BT50/BT55/BT70, Gansow 512ET, Comac), liftar, AGV-fordon, solcellslagring.",
    recommendedCharger: "NOCO GX2440 (24V) vid par-koppling, eller chAmp Pro 12V/30A för enstaka batteri. Välj alltid GEL-laddprofil.",
    seoKeywords: "Sonnenschein GF12105V, gelbatteri 12V 105Ah, batteri Nilfisk BA451, Sonnenschein dryfit, städmaskinsbatteri 12V premium, GF 12 105 V pris",
  },

  // ===== STATIONÄRA (2 st) =====
  {
    slug: "gf-12-050v",
    name: "Sonnenschein GF1250V – Gelbatteri 12V 50Ah",
    shortName: "GF 12V 50Ah",
    category: "stationara",
    voltage: "12V",
    capacity: "50 Ah (C5) / 55 Ah (C20)",
    price: 1756,
    images: ["/produkter/gf12050v.jpg"],
    badge: null,
    description:
      "Sonnenschein GF 12 050 V är ett kompakt gelbatteri med 50 Ah kapacitet (C5) och 55 Ah (C20) från den tyska tillverkaren Sonnenschein – pionjären inom gelbaserad batteriteknologi sedan 1950-talet. Med den patenterade dryfit-teknologin är batterisyran bunden i en gelé som aldrig behöver fyllas på.\n\nBatteriet är klassificerat som nonspillable och kan monteras i alla positioner utan risk för läckage. Det bildar inga oxiderande eller illaluktande gaser vid laddning, vilket gör det säkert att placera i slutna utrymmen som inuti städmaskiner eller under rullstolssäten.\n\nGF1250V levererar 700 cykler vid 75% urladdningsdjup enligt IEC 60254-1, vilket innebär att batteriet håller i många år vid daglig användning. Den extremt låga självurladdningen (under 2% per månad) gör det även lämpligt som reservkraftsbatteri.\n\nSonnenschein GF-V-serien är specifikt konstruerad för tuffa industriella miljöer – från städmaskiner och förarlösa transportfordon till lyftplattformar och elrullstolar. Made in Germany med över 130 års batteriexpertis.",
    inStock: true,
    specs: {
      Spänning: "12V",
      "Kapacitet (C5)": "50 Ah",
      "Kapacitet (C20)": "55 Ah",
      Artikelnummer: "GF1250V",
      Mått: "278 × 175 × 190 mm",
      Vikt: "19 kg",
      Poltyp: "Konisk",
      Typ: "Gel (dryfit), helt underhållsfri",
      Cykellivslängd: "700 cykler (IEC 60254-1, 75% DOD)",
      "Max laddström": "20 A",
      Drifttemperatur: "-30°C till +50°C",
      Tillverkad: "Tyskland",
      Varumärke: "Sonnenschein",
    },
    metaDescription: "Sonnenschein GF1250V: Tysktillverkat 12V 50Ah gelbatteri med dryfit-teknologi. 700 cykler, helt underhållsfritt. För städmaskiner och mobility.",
    fitsTo: "Gångbakom-städmaskiner (Nilfisk SC250, Hako Scrubmaster B12, Kärcher BR 35/12), elrullstolar, elmopeder/scootrar, solcellslagring, nödbelysning, UPS-system, larminstallationer.",
    recommendedCharger: "chAmp Pro 12V/15A (art.nr 0043880) – välj GEL-laddprofil.",
    seoKeywords: "Sonnenschein GF1250V, gelbatteri 12V 50Ah, batteri städmaskin kompakt, dryfit batteri, underhållsfritt 12V gel, rullstolsbatteri 12V",
  },
  {
    slug: "gf-12-160v",
    name: "Sonnenschein GF12160V – Gelbatteri 12V 160Ah",
    shortName: "GF 12V 160Ah",
    category: "stationara",
    voltage: "12V",
    capacity: "160 Ah (C5) / 196 Ah (C20)",
    price: 5276,
    images: ["/produkter/gf12160v.jpg"],
    badge: "Premium",
    description:
      "Sonnenschein GF 12 160 V är det största och kraftfullaste 12V-gelbatteriet i Sonnenscheins GF-V-sortiment med hela 160 Ah (C5) och 196 Ah (C20). Med 63 kg och måtten 518 × 274 × 238 mm är det ett batteri för riktigt tunga applikationer.\n\nTvå GF12160V i serie ger ett 24V-system med enorm kapacitet – perfekt för stora åkbara städmaskiner, tunga materialhanteringsfordon och industriella transportlösningar där driftstid är kritisk.\n\nSom alla Sonnenschein dryfit-batterier är GF12160V helt underhållsfritt, spillsäkert och gasningsfritt. Det kan placeras i slutna utrymmen utan ventilation och kräver aldrig vattenpåfyllning.\n\nMed 700 cyklers livslängd vid 75% urladdningsdjup och Sonnenscheins tyska kvalitetstillverkning är detta ett av de mest pålitliga industribatterierna på marknaden.",
    inStock: true,
    specs: {
      Spänning: "12V",
      "Kapacitet (C5)": "160 Ah",
      "Kapacitet (C20)": "196 Ah",
      Artikelnummer: "GF12160V",
      Mått: "518 × 274 × 238 mm",
      Vikt: "63 kg",
      Typ: "Gel (dryfit), helt underhållsfri",
      Cykellivslängd: "700 cykler",
      Tillverkad: "Tyskland",
      Varumärke: "Sonnenschein",
    },
    metaDescription: "Sonnenschein GF12160V: Kraftfullt 12V 160Ah gelbatteri. 700 cykler, 63 kg, Made in Germany. Det största 12V-gelbatteriet i GF-V-serien.",
    fitsTo: "Stora åkbara städmaskiner, tunga materialhanteringsfordon, industriella transportsystem, energilagring, reservkraft.",
    recommendedCharger: "NOCO GX2440 (24V/40A) vid par-koppling – GEL-profil.",
    seoKeywords: "Sonnenschein GF12160V, gelbatteri 12V 160Ah, stort industribatteri 12V, dryfit 12V premium, traktionsbatteri 12V 196Ah",
  },

  // ===== FRITID & SOLENERGI (4 st) =====
  {
    slug: "nm875-8et",
    name: "Nordmax NM875-8ET – Traktionsbatteri 8V 175Ah",
    shortName: "NM 8V 175Ah",
    category: "fritid-solenergi",
    voltage: "8V",
    capacity: "175 Ah (C20)",
    price: 2156,
    images: ["/produkter/nm875-8et.jpg"],
    badge: null,
    description:
      "Nordmax NM875-8ET är ett 8-volts traktionsbatteri med 175 Ah kapacitet, framtaget för golfbilar och lätta elfordon som använder 48V-drivlinor. Sex stycken NM875-8ET seriekopplade ger ett komplett 48V-system med hög energitäthet.\n\n8V-batterier erbjuder en optimal balans mellan kapacitet och vikt jämfört med 6V- och 12V-alternativen, och används i många populära golfbilsmodeller från Club Car, E-Z-GO och Yamaha.\n\nBatteriet följer BCI-gruppmått och ersätter direkt Trojan T-875 utan installationsanpassningar.",
    inStock: true,
    specs: {
      Spänning: "8V",
      "Kapacitet (C20)": "175 Ah",
      Artikelnummer: "NM875-8ET",
      Mått: "261 × 181 × 276 mm",
      Typ: "Blybatteri, öppet (fritt ventilerat)",
      Ersätter: "Trojan T-875",
      Varumärke: "Nordmax",
    },
    metaDescription: "Nordmax NM875-8ET: 8V 175Ah traktionsbatteri optimerat för golfbilar med 48V-system. Ersätter Trojan T-875. Snabb leverans i Sverige.",
    fitsTo: "Golfbilar med 48V-system (Club Car Precedent, E-Z-GO RXV/TXT, Yamaha Drive/G-MAX), lätta elfordon, utilityfordon.",
    recommendedCharger: "NOCO GX4820EU (48V/20A) för komplett 48V-system.",
    seoKeywords: "traktionsbatteri 8V 175Ah, batteri golfbil 8V, Nordmax NM875, ersätter Trojan T-875, 48V golfbilsbatteri",
  },
  {
    slug: "evgc6a-a-m8",
    name: "Discover EVGC6A-A – Dry Cell Traktionsbatteri 6V 220Ah",
    shortName: "Dry Cell 6V 220Ah",
    category: "fritid-solenergi",
    voltage: "6V",
    capacity: "220 Ah (C20)",
    price: 2636,
    images: ["/produkter/evgc6a.jpg"],
    badge: "Underhållsfri",
    description:
      "Discover EVGC6A-A är ett avancerat Dry Cell traktionsbatteri som kombinerar AGM-teknologi med Discovers patenterade hydropolymer-elektrolyt. Resultatet är ett helt underhållsfritt batteri som överträffar både traditionella våtbatterier och standard-gelbatterier i krävande traktionsapplikationer.\n\nMed 220 Ah kapacitet vid 6V levererar EVGC6A-A stabil energi genom hela arbetspasset. Den unika Dry Cell-teknologin innebär att elektrolyten är helt bunden i glasfibermattor – batteriet kan aldrig läcka, även om höljet skulle skadas. Det kräver ingen vattenpåfyllning och kan monteras i alla positioner.\n\nDiscover Dry Cell-batterier har använts och testats av världens största OEM-tillverkare i över tio år och är kända för sin extrema vibrationstålighet och långa livslängd även vid djupa urladdningar.\n\nBatteriet klarar upp till 1 000 cykler vid 50% urladdningsdjup, vilket gör det till ett av de mest hållbara alternativen på marknaden. Perfekt för miljöer där underhåll är svårt att genomföra eller där spillsäkerhet är kritiskt.",
    inStock: true,
    specs: {
      Spänning: "6V",
      "Kapacitet (C20)": "220 Ah",
      Artikelnummer: "EVGC6A-A-M8",
      Mått: "260 × 180 × 257 mm",
      Typ: "Dry Cell (VRLA/AGM med hydropolymer)",
      Underhåll: "Underhållsfri",
      Spillsäkert: "Ja – kan monteras i alla positioner",
      Livslängd: "Upp till 1 000 cykler (50% DOD)",
      Varumärke: "Discover",
    },
    metaDescription: "Discover EVGC6A-A: Underhållsfritt 6V 220Ah Dry Cell traktionsbatteri. Spillfritt, vibrationståligt. För städmaskiner, golfbilar och liftar.",
    fitsTo: "Städmaskiner (Nilfisk, Hako, Kärcher, Tennant, Comac), golfbilar, liftar (JLG, Genie), pallyftare, AGV-fordon, solcellslagring.",
    recommendedCharger: "NOCO GX2440 (24V) – välj AGM-läge vid laddning av Discover Dry Cell.",
    seoKeywords: "Discover Dry Cell 6V 220Ah, EVGC6A, underhållsfritt traktionsbatteri, spillfritt batteri städmaskin, AGM traktionsbatteri",
  },
  {
    slug: "evgc8a-a-m8",
    name: "Discover EVGC8A-A – Dry Cell Traktionsbatteri 8V 160Ah",
    shortName: "Dry Cell 8V 160Ah",
    category: "fritid-solenergi",
    voltage: "8V",
    capacity: "160 Ah (C20)",
    price: 2776,
    images: ["/produkter/evgc6a.jpg"],
    badge: null,
    description:
      "Discover EVGC8A-A är ett 8V Dry Cell traktionsbatteri med 160 Ah kapacitet, optimerat för golfbilar och lätta elfordon som använder 48V-system. Sex batterier i serie ger ett komplett och helt underhållsfritt drivsystem.\n\nDry Cell-teknologin innebär att du aldrig behöver kontrollera vätskenivåer eller fylla på destillerat vatten – en stor fördel i golfbilsanvändning där batteriet ofta är svåråtkomligt under sätet.\n\nMed sin säkerhet mot spill och vibrationer är EVGC8A-A även väl lämpat för utilityfordon och lätta transportmedel i industri och fastighetsskötsel.",
    inStock: true,
    specs: {
      Spänning: "8V",
      "Kapacitet (C20)": "160 Ah",
      Artikelnummer: "EVGC8A-A-M8",
      Mått: "260 × 180 × 286 mm",
      Typ: "Dry Cell (VRLA/AGM med hydropolymer)",
      Underhåll: "Underhållsfri",
      Spillsäkert: "Ja",
      Varumärke: "Discover",
    },
    metaDescription: "Discover EVGC8A-A: Underhållsfritt 8V 160Ah Dry Cell batteri för 48V-golfbilar. Spillfritt och vibrationståligt. Köp online.",
    fitsTo: "Golfbilar med 48V-system (Club Car, E-Z-GO, Yamaha), utilityfordon, lätta industrifordon, fastighetsskötsel.",
    recommendedCharger: "NOCO GX4820EU (48V/20A) i AGM-läge.",
    seoKeywords: "Discover Dry Cell 8V 160Ah, EVGC8A, golfbilsbatteri 8V underhållsfritt, 48V golfbil batteri, AGM traktionsbatteri 8V",
  },
  {
    slug: "gf-06-180v",
    name: "Sonnenschein GF6180V – Gelbatteri 6V 180Ah",
    shortName: "GF 6V 180Ah",
    category: "fritid-solenergi",
    voltage: "6V",
    capacity: "180 Ah (C5) / 200 Ah (C20)",
    price: 3168,
    images: ["/produkter/gf06180v.jpg", "/produkter/gf06180v-alt.jpg"],
    badge: null,
    description:
      "Sonnenschein GF 06 180 V är ett kraftfullt 6V gelbatteri med 180 Ah kapacitet (C5) som kombinerar Sonnenscheins beprövade dryfit-teknologi med robust industriell konstruktion. Batteriet är framtaget för tunga cykliska applikationer.\n\nMed 6V-spänning seriekopplas typiskt fyra GF6180V för ett 24V-system eller sex för 36V. Batteriets kompakta mått (246 × 192 × 275 mm) och 31 kg vikt gör det hanterbart vid installation och service.\n\nGelteknologin innebär att batteriet aldrig sulfaterar på samma sätt som våtbatterier – det finns ingen syraskiktning och inga gaser vid normal laddning. Helt underhållsfritt under hela batteriets livstid.",
    inStock: true,
    specs: {
      Spänning: "6V",
      "Kapacitet (C5)": "180 Ah",
      "Kapacitet (C20)": "200 Ah",
      Artikelnummer: "GF6180V",
      Mått: "246 × 192 × 275 mm",
      Vikt: "31 kg",
      Typ: "Gel (dryfit), helt underhållsfri",
      Cykellivslängd: "700 cykler",
      Tillverkad: "Tyskland",
      Varumärke: "Sonnenschein",
    },
    metaDescription: "Sonnenschein GF6180V: Robust 6V 180Ah gelbatteri med dryfit-teknologi. 700 cykler, underhållsfritt. Made in Germany. Köp online.",
    fitsTo: "Åkbara städmaskiner, golfbilar, liftar, materialhantering, förarlösa transportsystem (AGV/FTS), solcellssystem.",
    recommendedCharger: "NOCO GX2440 (24V/40A) eller GX3626EU (36V) – GEL-profil.",
    seoKeywords: "Sonnenschein GF6180V, gelbatteri 6V 180Ah, dryfit 6V, underhållsfritt 6V batteri, städmaskinsbatteri 6V gel",
  },
]

// ─── Helpers ───

export function getProductsByCategory(slug) {
  return products.filter((p) => p.category === slug)
}

export function getProductBySlug(slug) {
  return products.find((p) => p.slug === slug) || null
}

export function getProductImage(product) {
  return product.images?.[0] || "/produkter/placeholder.jpg"
}
