export const products = [
  // ===== TRAKTION & INDUSTRI (7 st) =====
  {
    slug: "nm125-6et",
    name: "Nordmax Traction 6V 240Ah",
    shortName: "NM 6V 240Ah",
    category: "traktion-industri",
    voltage: "6V",
    capacity: "240 Ah",
    price: 3790,
    images: ["/produkter/nm125-6et.jpg"],
    badge: "Populär",
    description:
      "Kraftfullt 6V traktionsbatteri med 240Ah kapacitet. Idealiskt för truckar, golfbilar och andra elfordon som kräver pålitlig energi under långa arbetspass. Tål djupa urladdningscykler.",
    inStock: true,
    specs: {
      Spänning: "6V",
      Kapacitet: "240 Ah",
      Artikelnummer: "NM125-6ET",
      Mått: "260 × 180 × 279 mm",
      Typ: "Blybatteri (flooded)",
      Varumärke: "Nordmax",
    },
  },
  {
    slug: "nm305g-et",
    name: "Nordmax Traction 6V 330Ah",
    shortName: "NM 6V 330Ah",
    category: "traktion-industri",
    voltage: "6V",
    capacity: "330 Ah",
    price: 5490,
    images: ["/produkter/nm305g-et.jpg"],
    badge: null,
    description:
      "Starkare 6V-variant med 330Ah för maskiner som kräver mer uthållighet. Robusta plattor och förstärkt hölje gör batteriet idealiskt för tunga cykler i lager- och industrimiljö.",
    inStock: true,
    specs: {
      Spänning: "6V",
      Kapacitet: "330 Ah",
      Artikelnummer: "NM305G-ET",
      Mått: "296 × 176 × 366 mm",
      Typ: "Blybatteri (flooded)",
      Varumärke: "Nordmax",
    },
  },
  {
    slug: "nml16h-et",
    name: "Nordmax Traction 6V 420Ah",
    shortName: "NM 6V 420Ah",
    category: "traktion-industri",
    voltage: "6V",
    capacity: "420 Ah",
    price: 6990,
    images: ["/produkter/nml16h-et.jpg"],
    badge: "Mest kraft",
    description:
      "Nordmax flaggskepp för tunga applikationer. 420Ah ger exceptionell drifttid för stora truckar och industrifordon. Vikt ca 52 kg. Byggd för krävande miljöer där maximalt antal drifttimmar är avgörande.",
    inStock: true,
    specs: {
      Spänning: "6V",
      Kapacitet: "420 Ah",
      Artikelnummer: "NML16H-ET",
      Mått: "296 × 176 × 425 mm",
      Vikt: "ca 52 kg",
      Typ: "Blybatteri (flooded)",
      Varumärke: "Nordmax",
    },
  },
  {
    slug: "nm1275-12et",
    name: "Nordmax Traction 12V 150Ah",
    shortName: "NM 12V 150Ah",
    category: "traktion-industri",
    voltage: "12V",
    capacity: "150 Ah",
    price: 5490,
    images: ["/produkter/nm1275-12et.jpg"],
    badge: null,
    description:
      "Kompakt 12V traktionsbatteri med 150Ah. Perfekt för mindre truckar, pallyftare och entreprenadmaskiner som behöver hög spänning i ett enda batteriblock. Enkel installation.",
    inStock: true,
    specs: {
      Spänning: "12V",
      Kapacitet: "150 Ah",
      Artikelnummer: "NM1275-12ET",
      Mått: "328 × 180 × 279 mm",
      Typ: "Blybatteri (flooded)",
      Varumärke: "Nordmax",
    },
  },
  {
    slug: "ev305a-a-am",
    name: "Discover Dry Cell 6V 330Ah",
    shortName: "Dry Cell 6V 330Ah",
    category: "traktion-industri",
    voltage: "6V",
    capacity: "330 Ah",
    price: 7490,
    images: ["/produkter/ev305a.jpg"],
    badge: "Underhållsfri",
    description:
      "Kraftfullt 330Ah Dry Cell-batteri för tunga cykliska applikationer. Helt underhållsfritt med förslutet design. Utmärkt för truckar och industriella elfordon som kräver maximal drifttid utan underhåll.",
    inStock: true,
    specs: {
      Spänning: "6V",
      Kapacitet: "330 Ah",
      Artikelnummer: "EV305A-A-AM",
      Mått: "295 × 180 × 345 mm",
      Typ: "Dry Cell (AGM)",
      Underhåll: "Underhållsfri",
      Varumärke: "Discover",
    },
  },
  {
    slug: "evl16a-a-m8",
    name: "Discover Dry Cell 6V 390Ah",
    shortName: "Dry Cell 6V 390Ah",
    category: "traktion-industri",
    voltage: "6V",
    capacity: "390 Ah",
    price: 8490,
    images: ["/produkter/evl16a.jpg"],
    badge: null,
    description:
      "Discovers mest kapacitetsstarka 6V-modell. 390Ah räcker för de mest krävande tillämpningarna — stora truckar, tunga städmaskiner och off-grid system. Helt underhållsfritt och läckagefritt.",
    inStock: true,
    specs: {
      Spänning: "6V",
      Kapacitet: "390 Ah",
      Artikelnummer: "EVL16A-A-M8",
      Mått: "295 × 180 × 385 mm",
      Typ: "Dry Cell (AGM)",
      Underhåll: "Underhållsfri",
      Varumärke: "Discover",
    },
  },
  {
    slug: "gf-06-240v",
    name: "Sonnenschein GF 6V 240Ah",
    shortName: "GF 6V 240Ah",
    category: "traktion-industri",
    voltage: "6V",
    capacity: "240 Ah",
    price: 7990,
    images: ["/produkter/gf06240v.jpg"],
    badge: null,
    description:
      "Sonnenscheins tyngsta 6V gel-batteri. 240Ah ger maximal drifttid för truckar och tunga industrifordon. Gel-teknologin eliminerar underhåll och risk för syraläckage helt.",
    inStock: true,
    specs: {
      Spänning: "6V",
      Kapacitet: "240 Ah",
      Artikelnummer: "GF6240V",
      Mått: "311 × 183 × 358 mm",
      Typ: "Gel (dryfit)",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Varumärke: "Sonnenschein",
    },
  },

  // ===== STÄDMASKINER (4 st) =====
  {
    slug: "nm105-6et",
    name: "Nordmax Traction 6V 225Ah",
    shortName: "NM 6V 225Ah",
    category: "stadmaskiner",
    voltage: "6V",
    capacity: "225 Ah",
    price: 3490,
    images: ["/produkter/nm105-6et.jpg"],
    badge: "Prisvärd",
    description:
      "Robust traktionsbatteri för golfbilar, städmaskiner och ledstaplare. Nordmax Traction-serien är designad för cyklisk användning med hög kapacitet och lång livslängd. Perfekt för daglig drift.",
    inStock: true,
    specs: {
      Spänning: "6V",
      Kapacitet: "225 Ah",
      Artikelnummer: "NM105-6ET",
      Mått: "260 × 180 × 279 mm",
      Typ: "Blybatteri (flooded)",
      Varumärke: "Nordmax",
    },
  },
  {
    slug: "gf-12-063y",
    name: "Sonnenschein GF 12V 63Ah",
    shortName: "GF 12V 63Ah",
    category: "stadmaskiner",
    voltage: "12V",
    capacity: "63 Ah",
    price: 4290,
    images: ["/produkter/gf1263y.jpg"],
    badge: null,
    description:
      "Mångsidigt 63Ah gel-batteri för städmaskiner, hissar och reservkraft. Y-serien tål upp till 1200 cykler vid 60% urladdning. Tysktillverkat med Sonnenscheins välkända kvalitet.",
    inStock: true,
    specs: {
      Spänning: "12V",
      Kapacitet: "63 Ah",
      Artikelnummer: "GF1263Y",
      Mått: "261 × 171 × 210 mm",
      Typ: "Gel (dryfit)",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Varumärke: "Sonnenschein",
    },
  },
  {
    slug: "gf-12-076v",
    name: "Sonnenschein GF 12V 76Ah",
    shortName: "GF 12V 76Ah",
    category: "stadmaskiner",
    voltage: "12V",
    capacity: "76 Ah",
    price: 5290,
    images: ["/produkter/gf12076v.jpg"],
    badge: null,
    description:
      "Pålitligt 76Ah gel-batteri för medelstora städmaskiner och stationära system. V-serien är optimerad för standby- och cyklisk drift. Lång livslängd och extremt låg självurladdning.",
    inStock: true,
    specs: {
      Spänning: "12V",
      Kapacitet: "76 Ah",
      Artikelnummer: "GF1276V",
      Mått: "330 × 171 × 236 mm",
      Typ: "Gel (dryfit)",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Varumärke: "Sonnenschein",
    },
  },
  {
    slug: "gf-12-105v",
    name: "Sonnenschein GF 12V 105Ah",
    shortName: "GF 12V 105Ah",
    category: "stadmaskiner",
    voltage: "12V",
    capacity: "105 Ah",
    price: 6990,
    images: ["/produkter/gf12105v.png"],
    badge: "Bästsäljare",
    description:
      "Sonnenscheins mest populära modell. 105Ah ger utmärkt kapacitet för större städmaskiner, truckar och off-grid solsystem. Beprövad gel-teknologi med designlivslängd på 10+ år.",
    inStock: true,
    specs: {
      Spänning: "12V",
      Kapacitet: "105 Ah",
      Artikelnummer: "GF12105V",
      Mått: "345 × 174 × 283 mm",
      Typ: "Gel (dryfit)",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Varumärke: "Sonnenschein",
    },
  },

  // ===== STATIONÄRA (4 st) =====
  {
    slug: "gf-12-050v",
    name: "Sonnenschein GF 12V 50Ah",
    shortName: "GF 12V 50Ah",
    category: "stationara",
    voltage: "12V",
    capacity: "50 Ah",
    price: 3290,
    images: ["/produkter/gf12050v.jpg"],
    badge: null,
    description:
      "Kompakt 12V gel-batteri för permobiler, larmsystem och mindre stationära tillämpningar. Sonnenschein dryfit-teknologi ger lång livslängd och är helt underhållsfritt. Designlivslängd 7+ år.",
    inStock: true,
    specs: {
      Spänning: "12V",
      Kapacitet: "50 Ah",
      Artikelnummer: "GF1250V",
      Mått: "278 × 175 × 190 mm",
      Typ: "Gel (dryfit)",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Varumärke: "Sonnenschein",
    },
  },
  {
    slug: "gf-12-052y",
    name: "Sonnenschein GF 12V 52Ah",
    shortName: "GF 12V 52Ah",
    category: "stationara",
    voltage: "12V",
    capacity: "52 Ah",
    price: 3590,
    images: ["/produkter/gf1252y.png"],
    badge: null,
    description:
      "Gel-batteri med hög cyklisk prestanda. Perfekt för rullstolar, städmaskiner och UPS-system. Sonnenschein Y-serien är optimerad för applikationer med frekventa urladdningar.",
    inStock: true,
    specs: {
      Spänning: "12V",
      Kapacitet: "52 Ah",
      Artikelnummer: "GF1252Y",
      Mått: "261 × 170 × 178 mm",
      Typ: "Gel (dryfit)",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Varumärke: "Sonnenschein",
    },
  },
  {
    slug: "gf-12-160v",
    name: "Sonnenschein GF 12V 160Ah",
    shortName: "GF 12V 160Ah",
    category: "stationara",
    voltage: "12V",
    capacity: "160 Ah",
    price: 9990,
    images: ["/produkter/gf12160v.jpg"],
    badge: "Premium",
    description:
      "Kraftpaket med 160Ah i 12V. Idealiskt för stora städmaskiner, off-grid solsystem och tunga stationära applikationer. Ett av Sonnenscheins mest kapacitetsstarka 12V-batterier.",
    inStock: true,
    specs: {
      Spänning: "12V",
      Kapacitet: "160 Ah",
      Artikelnummer: "GF12160V",
      Mått: "518 × 274 × 238 mm",
      Typ: "Gel (dryfit)",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Varumärke: "Sonnenschein",
    },
  },
  {
    slug: "gf-06-160v",
    name: "Sonnenschein GF 6V 160Ah",
    shortName: "GF 6V 160Ah",
    category: "stationara",
    voltage: "6V",
    capacity: "160 Ah",
    price: 4990,
    images: ["/produkter/gf06180v.jpg"],
    badge: null,
    description:
      "6V gel-batteri med 160Ah för traktionsapplikationer. Används i truckar, golfbilar och industrifordon. Underhållsfritt med Sonnenscheins dryfit-gel som tål djupa urladdningar.",
    inStock: true,
    specs: {
      Spänning: "6V",
      Kapacitet: "160 Ah",
      Artikelnummer: "GF6160V",
      Mått: "246 × 192 × 275 mm",
      Typ: "Gel (dryfit)",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Varumärke: "Sonnenschein",
    },
  },

  // ===== FRITID & SOLENERGI (4 st) =====
  {
    slug: "nm875-8et",
    name: "Nordmax Traction 8V 175Ah",
    shortName: "NM 8V 175Ah",
    category: "fritid-solenergi",
    voltage: "8V",
    capacity: "175 Ah",
    price: 3890,
    images: ["/produkter/nm875-8et.jpg"],
    badge: null,
    description:
      "8-volts traktionsbatteri optimerat för golfbilar och elfordon med 8V-system. 175Ah ger tillräcklig kapacitet för en hel dags användning. Underhållsvänlig design.",
    inStock: true,
    specs: {
      Spänning: "8V",
      Kapacitet: "175 Ah",
      Artikelnummer: "NM875-8ET",
      Mått: "261 × 181 × 276 mm",
      Typ: "Blybatteri (flooded)",
      Varumärke: "Nordmax",
    },
  },
  {
    slug: "evgc6a-a-m8",
    name: "Discover Dry Cell 6V 220Ah",
    shortName: "Dry Cell 6V 220Ah",
    category: "fritid-solenergi",
    voltage: "6V",
    capacity: "220 Ah",
    price: 4990,
    images: ["/produkter/evgc6a.jpg"],
    badge: "Underhållsfri",
    description:
      "Underhållsfritt Dry Cell-batteri med AGM-teknologi. Läckagefritt och vibrationståligt — perfekt för golfbilar, städmaskiner och solenergi. Kräver ingen vattenpåfyllning och kan monteras i alla lägen.",
    inStock: true,
    specs: {
      Spänning: "6V",
      Kapacitet: "220 Ah",
      Artikelnummer: "EVGC6A-A-M8",
      Mått: "260 × 180 × 257 mm",
      Typ: "Dry Cell (AGM)",
      Underhåll: "Underhållsfri",
      Varumärke: "Discover",
    },
  },
  {
    slug: "evgc8a-a-m8",
    name: "Discover Dry Cell 8V 160Ah",
    shortName: "Dry Cell 8V 160Ah",
    category: "fritid-solenergi",
    voltage: "8V",
    capacity: "160 Ah",
    price: 4990,
    images: ["/produkter/evgc6a.jpg"],
    badge: null,
    description:
      "8V Dry Cell för golfbilar och elfordon. Underhållsfri AGM-teknologi med djupcykelkapacitet. Kan monteras i valfri position och kräver ingen vattenpåfyllning under hela livslängden.",
    inStock: true,
    specs: {
      Spänning: "8V",
      Kapacitet: "160 Ah",
      Artikelnummer: "EVGC8A-A-M8",
      Mått: "260 × 180 × 286 mm",
      Typ: "Dry Cell (AGM)",
      Underhåll: "Underhållsfri",
      Varumärke: "Discover",
    },
  },
  {
    slug: "gf-06-180v",
    name: "Sonnenschein GF 6V 180Ah",
    shortName: "GF 6V 180Ah",
    category: "fritid-solenergi",
    voltage: "6V",
    capacity: "180 Ah",
    price: 5490,
    images: ["/produkter/gf06180v.jpg", "/produkter/gf06180v-alt.jpg"],
    badge: null,
    description:
      "Uppgraderad 6V-modell med 180Ah för maskiner som behöver extra drifttid. Samma kompakta format som GF6160V men med 12% mer kapacitet. Populärt val för husbil, båt och solenergi.",
    inStock: true,
    specs: {
      Spänning: "6V",
      Kapacitet: "180 Ah",
      Artikelnummer: "GF6180V",
      Mått: "246 × 192 × 275 mm",
      Typ: "Gel (dryfit)",
      Underhåll: "Underhållsfri",
      Tillverkad: "Tyskland",
      Varumärke: "Sonnenschein",
    },
  },
]

// ─── Helpers ───

export function getProductsByCategory(slug) {
  return products.filter((p) => p.category === slug)
}

export function getProductBySlug(slug) {
  return products.find((p) => p.slug === slug) || null
}

export function getProductImage(product) {
  return product.images?.[0] || "/produkter/placeholder.jpg"
}
